[main]
; Accent color
button-active = "d12874"
button-highlight = "c00264"
button = "d12874"

; Content wrapper color
sidebar = "120513"
base = "120513"

; Content background color
main = "261627"

; Search / custom apps buttons
main-elevated = "1e0e1f"

; Search / custom apps buttons HOVER / FOCUS
highlight-elevated = "1e0f1f"

; Shadow color
shadow = "261627"

; Titles
text = "f1dcf1"

; Secondary accent / text color
text-subdued = "dec9de"

; Dropdown / misc
card = "1e0f1f"


    ; --spice-button: #1db954;
    ; --spice-highlight: #1a1a1a;
    ; --spice-notification-error: #e22134;
    ; --spice-highlight-elevated: #2a2a2a;
    ; --spice-main: #121212;
    ; --spice-sidebar: #000000;
    ; --spice-shadow: #000000;
    ; --spice-card: #282828;
    ; --spice-main-elevated: #242424;
    ; --spice-misc: #7f7f7f;
    ; --spice-tab-active: #333333;
    ; --spice-selected-row: #797979;
    ; --spice-button-active: #1ed760;
    ; --spice-subtext: #b3b3b3;
    ; --spice-button-disabled: #535353;
    ; --spice-text: #ffffff;
    ; --spice-player: #181818;
    ; --spice-notification: #4687d6;
    ; --spice-rgb-button: 29, 185, 84;
    ; --spice-rgb-highlight: 26, 26, 26;
    ; --spice-rgb-notification-error: 226, 33, 52;
    ; --spice-rgb-highlight-elevated: 42, 42, 42;
    ; --spice-rgb-main: 18, 18, 18;
    ; --spice-rgb-sidebar: 0, 0, 0;
    ; --spice-rgb-shadow: 0, 0, 0;
    ; --spice-rgb-card: 40, 40, 40;
    ; --spice-rgb-main-elevated: 36, 36, 36;
    ; --spice-rgb-misc: 127, 127, 127;
    ; --spice-rgb-tab-active: 51, 51, 51;
    ; --spice-rgb-selected-row: 121, 121, 121;
    ; --spice-rgb-button-active: 30, 215, 96;
    ; --spice-rgb-subtext: 179, 179, 179;
    ; --spice-rgb-button-disabled: 83, 83, 83;
    ; --spice-rgb-text: 255, 255, 255;
    ; --spice-rgb-player: 24, 24, 24;
    ; --spice-rgb-notification: 70, 135, 214;
